export enum AuditActionType {
  CREATE = 'CREATE',
  UPDATE = 'UPDATE',
  DELETE = 'DELETE',
  APPROVE = 'APPROVE',
  CANCEL = 'CANCEL',
  STATUS_CHANGE = 'STATUS_CHANGE',
  STOCK_IN = 'STOCK_IN',
  STOCK_OUT = 'STOCK_OUT',
  TRANSFER = 'TRANSFER',
  SHIPMENT = 'SHIPMENT',
  LOGIN = 'LOGIN',
  EXPORT = 'EXPORT'
}
